"""add admin settings table

Revision ID: add_admin_settings
Revises: e6bb583aac2d
Create Date: 2025-08-29 21:32:47.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_admin_settings"
down_revision = "e6bb583aac2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_scanning_primary_provider", sa.String(), nullable=True),
        sa.Column("image_scanning_secondary_provider", sa.String(), nullable=True),
        sa.Column("image_scanning_enable_ocr_fallback", sa.Boolean(), nullable=False),
        sa.Column("openai_api_key", sa.Text(), nullable=True),
        sa.Column("anthropic_api_key", sa.Text(), nullable=True),
        sa.Column("gemini_api_key", sa.Text(), nullable=True),
        sa.Column("ollama_base_url", sa.String(), nullable=True),
        sa.Column("openai_model", sa.String(), nullable=True),
        sa.Column("anthropic_model", sa.String(), nullable=True),
        sa.Column("gemini_model", sa.String(), nullable=True),
        sa.Column("ollama_model", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Insert default settings row
    op.execute(
        """
        INSERT INTO admin_settings (
            image_scanning_primary_provider,
            image_scanning_secondary_provider,
            image_scanning_enable_ocr_fallback,
            openai_model,
            anthropic_model,
            gemini_model,
            ollama_model,
            ollama_base_url
        ) VALUES (
            'none',
            'none',
            true,
            'gpt-4o-mini',
            'claude-3-haiku-20240307',
            'gemini-1.5-flash',
            'llava',
            'http://localhost:11434'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_settings")
    # ### end Alembic commands ###