"""add mcp oauth clients, requests, codes, tokens and api token grants

Revision ID: 970cf50b85f4
Revises: 7f3d2a91c6e8
Create Date: 2026-10-03 15:24:25.812574

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "970cf50b85f4"
down_revision: str | None = "7f3d2a91c6e8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_oauth_clients",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret_hash", sa.String(), nullable=True),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column("pkce_optional", sa.Boolean(), nullable=False),
        sa.Column("allow_write_scope", sa.Boolean(), nullable=False),
        sa.Column("redirect_uris", sa.Text(), nullable=False),
        sa.Column("created_by", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("last_used_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_oauth_clients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_oauth_clients_client_id"), ["client_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_clients_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_clients_created_by"), ["created_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_clients_group_id"), ["group_id"], unique=False)

    op.create_table(
        "mcp_api_token_grants",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("long_live_token_id", sa.Integer(), nullable=False),
        sa.Column("allow_writes", sa.Boolean(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["long_live_token_id"],
            ["long_live_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_api_token_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_api_token_grants_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mcp_api_token_grants_long_live_token_id"), ["long_live_token_id"], unique=True
        )

    op.create_table(
        "mcp_oauth_codes",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("oauth_client_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("redirect_uri_provided", sa.Boolean(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("code_challenge", sa.String(), nullable=True),
        sa.Column("expires_at", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("family_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["oauth_client_id"],
            ["mcp_oauth_clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_oauth_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_oauth_codes_code_hash"), ["code_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_codes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_codes_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_codes_oauth_client_id"), ["oauth_client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_codes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mcp_oauth_requests",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("handle_hash", sa.String(), nullable=False),
        sa.Column("oauth_client_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("redirect_uri_provided", sa.Boolean(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("code_challenge", sa.String(), nullable=True),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("expires_at", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["oauth_client_id"],
            ["mcp_oauth_clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_oauth_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_oauth_requests_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_requests_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_requests_handle_hash"), ["handle_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_requests_oauth_client_id"), ["oauth_client_id"], unique=False)

    op.create_table(
        "mcp_oauth_tokens",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("oauth_client_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("family_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("expires_at", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("granted_at", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("revoked_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("last_used_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["oauth_client_id"],
            ["mcp_oauth_clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_oauth_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_family_id"), ["family_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_oauth_client_id"), ["oauth_client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_revoked_at"), ["revoked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_mcp_oauth_tokens_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mcp_oauth_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_oauth_client_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_family_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_expires_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_tokens_created_at"))

    op.drop_table("mcp_oauth_tokens")
    with op.batch_alter_table("mcp_oauth_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_requests_oauth_client_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_requests_handle_hash"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_requests_expires_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_requests_created_at"))

    op.drop_table("mcp_oauth_requests")
    with op.batch_alter_table("mcp_oauth_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_codes_user_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_codes_oauth_client_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_codes_expires_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_codes_created_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_codes_code_hash"))

    op.drop_table("mcp_oauth_codes")
    with op.batch_alter_table("mcp_api_token_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_api_token_grants_long_live_token_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_api_token_grants_created_at"))

    op.drop_table("mcp_api_token_grants")
    with op.batch_alter_table("mcp_oauth_clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_clients_group_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_clients_created_by"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_clients_created_at"))
        batch_op.drop_index(batch_op.f("ix_mcp_oauth_clients_client_id"))

    op.drop_table("mcp_oauth_clients")
    # ### end Alembic commands ###
