"""add recipe card ingestion jobs, batches, settings, notifier options, provider runs_locally and usage job_id

Revision ID: cc5357be7e71
Revises: 970cf50b85f4
Create Date: 2026-10-03 23:18:42.112836

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "cc5357be7e71"
down_revision: str | None = "970cf50b85f4"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_ingestion_batches",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("created_by", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("last_upload_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("sealed_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("notified_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_ingestion_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_batches_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_batches_group_id"), ["group_id"], unique=False)
        batch_op.create_index(
            "ix_recipe_ingestion_batches_household_source_sealed",
            ["household_id", "source", "sealed_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_batches_household_id"), ["household_id"], unique=False)

    op.create_table(
        "recipe_ingestion_jobs",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("batch_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_by", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("committed_by", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("integration_id", sa.String(), nullable=True),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("local_only", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("draft_version", sa.Integer(), nullable=False),
        sa.Column("extracted_version", sa.Integer(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("task_kind", sa.String(length=16), nullable=True),
        sa.Column("task_state", sa.String(length=16), nullable=True),
        sa.Column("task_priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("rate_limit_retries", sa.Integer(), nullable=False),
        sa.Column("task_payload", sa.Text(), nullable=True),
        sa.Column("not_before", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("lease_expires_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("task_started_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("lease_token", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("progress_key", sa.String(length=64), nullable=True),
        sa.Column("pages", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.Column("extraction", sa.Text(), nullable=True),
        sa.Column("draft", sa.Text(), nullable=True),
        sa.Column("flags", sa.Text(), nullable=True),
        sa.Column("proposals", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_params", sa.Text(), nullable=True),
        sa.Column("commit_recipe_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("commit_asset_token", sa.String(length=32), nullable=True),
        sa.Column("commit_started_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("committed_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["recipe_ingestion_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_ingestion_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index("ix_recipe_ingestion_jobs_batch_position", ["batch_id", "position"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_household_id"), ["household_id"], unique=False)
        batch_op.create_index(
            "ix_recipe_ingestion_jobs_household_source_sha256", ["household_id", "source_sha256"], unique=False
        )
        batch_op.create_index(
            "ix_recipe_ingestion_jobs_household_status_created",
            ["household_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_recipe_id"), ["recipe_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_recipe_ingestion_jobs_task_state_priority_created",
            ["task_state", "task_priority", "created_at"],
            unique=False,
        )

    op.create_table(
        "recipe_ingestion_settings",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("local_only", sa.Boolean(), nullable=False),
        sa.Column("cross_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_ingestion_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_settings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingestion_settings_group_id"), ["group_id"], unique=True)

    op.create_table(
        "ai_event_notifier_options",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("notifier_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("recipe_ingestion_ready", sa.Boolean(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["notifier_id"],
            ["group_events_notifiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_event_notifier_options", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_event_notifier_options_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_event_notifier_options_notifier_id"), ["notifier_id"], unique=True)

    # Existing providers aren't local until a manager says so, so local-only cards fail closed
    with op.batch_alter_table("ai_providers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("runs_locally", sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table("ai_usage_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_ai_usage_log_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_usage_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_log_job_id"))
        batch_op.drop_column("job_id")

    with op.batch_alter_table("ai_providers", schema=None) as batch_op:
        batch_op.drop_column("runs_locally")

    with op.batch_alter_table("ai_event_notifier_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_event_notifier_options_notifier_id"))
        batch_op.drop_index(batch_op.f("ix_ai_event_notifier_options_created_at"))

    op.drop_table("ai_event_notifier_options")
    with op.batch_alter_table("recipe_ingestion_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_settings_group_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_settings_created_at"))

    op.drop_table("recipe_ingestion_settings")
    with op.batch_alter_table("recipe_ingestion_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_recipe_ingestion_jobs_task_state_priority_created")
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_recipe_id"))
        batch_op.drop_index("ix_recipe_ingestion_jobs_household_status_created")
        batch_op.drop_index("ix_recipe_ingestion_jobs_household_source_sha256")
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_household_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_group_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_created_at"))
        batch_op.drop_index("ix_recipe_ingestion_jobs_batch_position")
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_jobs_batch_id"))

    op.drop_table("recipe_ingestion_jobs")
    with op.batch_alter_table("recipe_ingestion_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_batches_household_id"))
        batch_op.drop_index("ix_recipe_ingestion_batches_household_source_sealed")
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_batches_group_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingestion_batches_created_at"))

    op.drop_table("recipe_ingestion_batches")
    # ### end Alembic commands ###
