"""add ai provider routes, usage log and encrypted api keys

Revision ID: 7f3d2a91c6e8
Revises: 3527efeeec34
Create Date: 2026-10-03 11:41:23.878988

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types
from mealie.core.root_logger import get_logger
from mealie.db.models._model_utils.encrypted import (
    SecretDecryptionError,
    decrypt_value,
    encrypt_value,
    is_encrypted,
)

# revision identifiers, used by Alembic.
revision = "7f3d2a91c6e8"
down_revision: str | None = "3527efeeec34"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

logger = get_logger()


def _api_keys() -> list[tuple]:
    return list(op.get_bind().execute(sa.text("SELECT id, api_key FROM ai_providers")).fetchall())


def _set_api_key(provider_id, api_key: str) -> None:
    op.get_bind().execute(
        sa.text("UPDATE ai_providers SET api_key = :api_key WHERE id = :id"),
        {"api_key": api_key, "id": provider_id},
    )


def encrypt_api_keys() -> None:
    """Encrypts the plaintext API keys stored before this revision"""
    encrypted = 0
    for provider_id, api_key in _api_keys():
        if api_key is None or is_encrypted(api_key):
            continue

        _set_api_key(provider_id, encrypt_value(api_key))
        encrypted += 1

    if encrypted:
        logger.info(f"Encrypted {encrypted} AI provider API key(s)")


def decrypt_api_keys() -> None:
    """Restores plaintext API keys, which is all that earlier revisions can read"""
    for provider_id, api_key in _api_keys():
        if api_key is None or not is_encrypted(api_key):
            continue

        try:
            plaintext = decrypt_value(api_key)
        except SecretDecryptionError:
            # Keep the ciphertext rather than lose it; restoring the matching .secret can still recover it
            logger.warning(f"Could not decrypt the API key of AI provider {provider_id}; leaving it as-is")
            continue

        _set_api_key(provider_id, plaintext)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_routes",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("settings_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("slot", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("provider_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["ai_provider_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("settings_id", "slot", "position", name="ai_provider_routes_settings_id_slot_position_key"),
        sa.UniqueConstraint(
            "settings_id", "slot", "provider_id", name="ai_provider_routes_settings_id_slot_provider_id_key"
        ),
    )
    with op.batch_alter_table("ai_provider_routes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_provider_routes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_provider_routes_provider_id"), ["provider_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_provider_routes_settings_id"), ["settings_id"], unique=False)

    op.create_table(
        "ai_usage_log",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("provider_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("protocol", sa.String(), nullable=False),
        sa.Column("slot", sa.String(), nullable=False),
        sa.Column("feature", sa.String(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_usage_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_usage_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_usage_log_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_usage_log_provider_id"), ["provider_id"], unique=False)

    with op.batch_alter_table("ai_providers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("protocol", sa.String(), server_default="openai", nullable=False))
        batch_op.add_column(sa.Column("monthly_token_limit", sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    # Unencrypted keys stay readable (they're read as plaintext), so a failure here is logged rather than
    # blocking startup; the keys are encrypted the next time they're saved.
    try:
        with op.get_bind().begin_nested():
            encrypt_api_keys()
    except Exception:
        logger.exception("Failed to encrypt AI provider API keys")


def downgrade():
    decrypt_api_keys()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_providers", schema=None) as batch_op:
        batch_op.drop_column("monthly_token_limit")
        batch_op.drop_column("protocol")

    with op.batch_alter_table("ai_usage_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_log_provider_id"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_log_group_id"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_log_created_at"))

    op.drop_table("ai_usage_log")
    with op.batch_alter_table("ai_provider_routes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_provider_routes_settings_id"))
        batch_op.drop_index(batch_op.f("ix_ai_provider_routes_provider_id"))
        batch_op.drop_index(batch_op.f("ix_ai_provider_routes_created_at"))

    op.drop_table("ai_provider_routes")
    # ### end Alembic commands ###
