import ast
import pathlib
import re
import subprocess
from dataclasses import dataclass, field

from utils import PROJECT_DIR, log, render_python_template

template = """# This file is auto-generated by gen_schema_exports.py
{% for file in data.module.files %}{{ file.import_str() }}
{% endfor %}

__all__ = [
    {% for name in data.names -%}
    "{{ name }}",
    {%- endfor %}
]

"""

SCHEMA_PATH = PROJECT_DIR / "mealie" / "schema"

SKIP = {"static", "__pycache__"}


class PyFile:
    import_path: str
    """The import path of the file"""

    classes: list[str]
    """A list of classes in the file"""

    def __init__(self, path: pathlib.Path):
        self.import_path = path.stem
        self.classes = []

        self.classes = PyFile.extract_classes(path)
        self.classes.sort()

    def import_str(self) -> str:
        """Returns a string that can be used to import the file"""
        return f"from .{self.import_path} import {', '.join(self.classes)}"

    @staticmethod
    def extract_classes(file_path: pathlib.Path) -> list[str]:
        name = file_path.stem

        if name == "__init__" or name.startswith("_"):
            return []

        classes = re.findall(r"(?m)^class\s(\w+)", file_path.read_text())
        return classes


@dataclass
class Modules:
    directory: pathlib.Path
    """The directory to search for modules"""

    files: list[PyFile] = field(default_factory=list)
    """A list of files in the directory"""

    def __post_init__(self):
        # fork: in file name order, not the filesystem's, so every machine generates the same file
        for file in sorted(self.directory.glob("*.py")):
            if file.name.startswith("_"):
                continue

            pfile = PyFile(file)

            if len(pfile.classes) > 0:
                self.files.append(pfile)

            else:
                log.debug(f"Skipping {file.name} as it has no classes")


def existing_exports(init_file: pathlib.Path) -> list[str]:
    """fork: the names a module's `__init__.py` already lists in `__all__`, in their order"""
    if not init_file.exists():
        return []
    for node in ast.parse(init_file.read_text()).body:
        if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.List | ast.Tuple):
            continue
        if any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            names = [elt.value for elt in node.value.elts if isinstance(elt, ast.Constant)]
            return [name for name in names if isinstance(name, str)]
    return []


def export_order(existing: list[str], names: list[str]) -> list[str]:
    """
    fork: `__all__` for `names`: the names already exported keep their order, and new ones follow, sorted. Generation is
    then the same on every machine and run, and an existing `__init__.py` changes only where a class came or went.
    """
    wanted = set(names)
    kept = list(dict.fromkeys(name for name in existing if name in wanted))
    return kept + sorted(wanted.difference(kept))


def find_modules(root: pathlib.Path) -> list[Modules]:
    """Finds all the top level modules in the provided folder"""
    modules: list[Modules] = []
    for file in root.iterdir():
        if file.is_dir() and file.name not in SKIP:
            modules.append(Modules(directory=file))

    return modules


def main() -> None:
    modules = find_modules(SCHEMA_PATH)

    template_paths: list[pathlib.Path] = []
    for module in modules:
        log.debug(f"Module: {module.directory.name}")
        for file in module.files:
            log.debug(f"  File: {file.import_path}")
            log.debug(f"    Classes: [{', '.join(file.classes)}]")

        template_path = module.directory / "__init__.py"
        template_paths.append(template_path)
        # fork: a stable `__all__` order (`export_order`)
        names = export_order(existing_exports(template_path), [name for file in module.files for name in file.classes])
        render_python_template(template, template_path, {"module": module, "names": names})

    # fork: a list, not a generator the first command would use up (leaving `ruff format` with no paths, so it formatted
    # the whole working directory and not these files)
    path_args = [str(p) for p in template_paths]
    subprocess.run(["uv", "run", "ruff", "check", *path_args, "--fix"])
    subprocess.run(["uv", "run", "ruff", "format", *path_args])


if __name__ == "__main__":
    main()
